### ISSUE TITLE
refine agreement table in 9.4.5, Immunity and Availability

### ISSUE THREAD

**Issue by dhh1128** [trustoverip/tswg-keri-specification#204]
As far as I can tell, the table that appears in this section contains columns adapted from figure 11.4 on page 98 of https://arxiv.org/pdf/1907.02143. However, the discussion that precedes the table, in this spec, does not explain the significance of 3F+1 or of (N+F+1)/2 in the analysis; readers would have to go to the PDF to understand them. If the text isn't going to explain those columns, I suggest that we remove them because they are confusing.

The table doesn't have a row for N=5, which confuses me. Perhaps this is because the introduction of F\* into the analysis makes this table diverge from the one in the whitepaper for some reason I don't understand?

The discussion in the spec introduces something that I don't see in the section on agreement in the PDF, which is the idea of availability. There is no mention of F\* in the whitepaper. If I understand the whitepaper correctly, "agreement" requires fully receipted proof by a sufficient number of witnesses, and requires the availability of the controller, so availability at the time the event was promulgated isn't the availability this section of the spec must be talking about -- right? But if it is talking about availability at the time the event is later queried, don't we just need to query any single witness that can prove prior agreement among at least M witnesses? If so, why is F* even mentioned?

I am happy to submit a rewrite, but I want to be sure I understand the intent here, before I do.

**Comment by SmithSamuelM** [comment]
@dhh1128 The relevant section starts with... It can be shown that for any set of N witnesses, (see [[ref: KERI-WP ]]) there is a threshold M < N that guarantees that at most one sufficient agreement occurs or none at all despite a dishonest controller but where at most F* = N-M of the witnesses are potentially unavailable and at most F < M is duplicitous.

The result comes from a formula that uses F, F*, M, and N. THis formula is not included in the spec because it is defined in the reference.  So this section of the Spec is citing a way for a controller to ensure sufficient agreement given faults. It is up to the controller to decide what policy it will be held accountable via the threshold and witness list. A validator can then decide if its sufficient for them to trust. In  this sense it is informative.

Likewise the table only lists some of the values one could generate with the formula and is not exhaustive. 

The phrase "It can be shown" tells the reader that the result is being cited but not explained or proven in detail as that would take several pages. It is assumed that if the reader wants to verify the result they need to be familiar with the cited reference. Similarly when the spec uses the word Internet it is assumed that the reader is familiar with the term.  

The question I struggled to answer when writing the spec was how much was enough for the spec. Specs aren't tutorials then are specs and have to make assumptions about the terminology.  I can see that another paragraph that goes into more detail on the difference between F and F* may be helpful but then so would a  tutorial on Byzantine Agreement algorithms.  

For example the white paper has this paragraph:

With the inequality above, there may be more than one solution for M for any given N and F. In that case, we can have an effective number of unavailable witnesses denoted F* which is given by 
	F* = N - M	(0.1)
There are two types of faults we care about with regard to F and F*. One type is unavailability, in which an otherwise honest witness is not available to publish a receipt for a first-seen event. The other type is duplicity, in which a witness publishes a receipt for more than one version of an event given more than one version of an event has been produced by a duplicitous or compromised controller. The inequality means that while no more than F witnesses are allowed to be duplicitous, in some cases  F* ≥ F honest witnesses may be unavailable.

But to understand what an HONEST witness is, versus a DUPLICITOUS witness requires yet more paragraphs.  

An alternative would be to simply cite the reference and state in the spec that a Controller MAY choose to use the KAWA algorthm for threshold selection and cite the reference and leave everything else out.  It is in an appendix as informative but not exhaustively so.

**Comment by SmithSamuelM** [comment]
FYI:   A duplicitous (maliciously dishonest ) witness could witness more than one version of the same event. This means that effectively the size of N is exanded. Suppose that N is 7 and M is 5 and F is 2 then when "voting" the two dishonest witnesses each vote to two different versions of the event this means that a total of 9 votes would be cast. 5 votes by the honest witnesses and 4 votes by the two dishonest witnesses. This means that 5 is still sufficient to guarantee that only one version can satisfy the threshold given at most two dishonest witnesses. But I could expand my witness pool N to 8 with a threhold of 5 by allowing at most a total of 3 faulty witnesses where 3 were faulty but unavailable not dishonest. This is F*.  So the controller determines what level and types of faults it wants to be responsible or held accountable for. The algorithm tells the controller and validators what the possibilities are given the N and M. It doesn't guarantee that they won't be more than F or F* faults, merely that at most, F or F* faults could occur and still guarantee agreement.

We can also consider combinations of F and F*.  Suppose at any given point in time we have at most 1 F dishonst witness and  at most 2 F* unavailable witnesses but we expand the N to be * and M = 5.  Now worst cases would be 1)  the 1 F votes twice and all the other 7 honest witness vote. This gives a total of 9 votes. The threshold of 5 is still a majority so we have a guarantee of agreement 2) The dishonest witness votes twice and two of the honest witnesses are unavailable. So we have 6 votes, (5 available honest and 2 from the one dishonest)  So we have either 5 votes that are in agreement or no agreement at all. The guarantee is that either there is one agreement or no agreement never multiple agreement.  

Now with a pool of 8 and a threshold of 5, I can't have two dishonest witnesses at the same time and still satisfy the guarantee. Becaause the number of votes worst case would be 6 honest + 4 (2 dishonest voting twice each) = 10 and 5 is not a majority.

The formula just informs the controller and validators what types and levels of faults are allowable given N and M.  
Ultimately although a Validator may hold the controller accountable for any duplicity of its witnesses. a Validator on  a high stakes event may choose to watch enough witnesses to guarantee the actual level of duplicity satisfies the validators trust level before making a trust decision.

**Comment by dhh1128** [comment]
In the version of the spec published at https://trustoverip.github.io/tswg-keri-specification, the reference to KERI-WP points at a term, not at an entry in the bibliography. When you hover, its URL is https://trustoverip.github.io/tswg-keri-specification/#term:keri-wp, I see now that what's checked in in the markdown has a biblref instead of a termref, so I would assume the intent was to point to item 4 in the bibliography? The string "KERI-WP" only occurs in the markdown at that one referencing location; there is no apparent referent for it. It seems that either the transformation process is generating URLs wrong, or we have stale content published.

The version of the KERI whitepaper that is referenced in both the published HTML and currently checked in markdown of the spec is v15 from arxiv.org: https://arxiv.org/pdf/1907.02143. In that version, some of what you quoted as whitepaper content doesn't appear. For example, I could not find the phrase "there may be more than one solution", and I could not find the string "F*". I assume that you are citing a newer version of your paper, perhaps the one published in your github repo? If so, should we update the link in the spec?

I get that the spec and the whitepaper have different purposes, and that the spec references the whitepaper to provide more context. However, I don't think the spec should minimize references to terms or mathematical expressions that cannot be understood from the spec itself. Perhaps that goal is not always possible, but in this case, I think it's easy to achieve. Either:

1. as you said in your final paragraph: simply cite the reference and state that a controller MAY choose to use the KAWA algorithm.
OR
2. remove the columns from your table that have a significance not explained in the spec: 3F+1 and (N+F+1)/2. 

I think less is more, so I have a preference for solution 1. But I'm happy to submit a PR for either solution.

**Comment by dhh1128** [comment]
>FYI: A duplicitous (maliciously dishonest ) witness

What is confusing to me in this explanation is the element of time. Does "voting" happen as witnesses are coming to agreement, or does it happen later, when a witness decides which version of reality to report to a validator? Is F*, which accounts for unavailable witnesses, accounting for witnesses that are unavailable at the time the controller promulgates the events and waits for agreement -- or to witnesses that are unavailable later, when a validator asks for the KEL?

**Comment by SmithSamuelM** [comment]
The spec should be referencing version 2.62 of the WhitePaper which is the one on my github repo.  
I can go either way on the table.

**Comment by dhh1128** [comment]
Okay, I'll raise a PR.

**Comment by SmithSamuelM** [comment]
I need to push 2.62 sorry

**Comment by SmithSamuelM** [comment]
A typical distributed consensus algorithm with a liveness guarantee is duplicity hiding. KAWA preserves the critical element of duplicity evident. 

What I mean by duplicity hiding is that one version of an event that is correctly signed will always be guaranteed within a time bound be agreed upon (subject to the fault constraint). Two correctly signed but different events are duplicity. But the ledger only ever provides one. 

This means a Validator never sees that there ever were alternate versions of that same event that were being voted upon but were discarded. Likewise a controller posting an event may never see that its keys have been compromised unless and until the compromised version of the event wins the voting and is the once accepted. By then it is too late.

Now from a systems design perspective how likely is F versus F*.  F is highly unlikely whlle F* is highly likely. So now informing the users about how to design for F* might be unsatisfying.  Nonetheless, F includes F* as a subset, just with a more stringent threshold, so assuming that F* never exceeds F is a conservative design constraint but may be too conservative. 

In order for a duplicitous witness fault to occur two key compromises  must have happened. A sufficient majority of the Controller's signing keys must be compromised and a given witness signing key must have been compromised.  Now a malicous attacker can publish a verifiable receipt for an alternate version of an event.  

In order for an unavailable witness fault to occur, no key compromise is needed, the witness just has to be offline.

**Comment by SmithSamuelM** [comment]
@dhh1128 I pushed the 2.62 version of the white paper.  it was updated in January.
